export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'

export const FETCH_QUIZ_START = 'FETCH_QUIZ_START'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR'
export const QUIZ_RETRY_STATE_RESET = 'QUIZ_RETRY_STATE_RESET'
export const QUIZ_FINISHED = 'QUIZ_FINISHED'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'

export const QUIZ_CREATE_PUSH_QUESTION = 'QIOZ_CREATE_PUSH_QUESTION'
export const QUIZ_CREATE_CLEAN_FORM = 'QUIZ_CREATE_CLEAN_FORM'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'